library(coda)
library(dplyr)
library(reshape2)
library(ggplot2)
library(purrr)
library(XML)

if (!interactive()) {
  args <- commandArgs(trailingOnly = TRUE)

  if (!length(args) == 2) {
    stop("Bad arguments!")
  }

  if (args[1] == "GP") {
    if (!is.element(args[2], c("GP_fixed_clock_0.3_epo_3"
                              ,"GP_fixed_clock_0.3_epo_4"
                              ,"GP_fixed_clock_1.1_epo_3"
                              ,"GP_fixed_clock_1.1_epo_4"))) {
      stop("Did not recognise the model: ", args[2])
    }
  } else if (args[1] == "RSA_BW") {
    if (!is.element(args[2], c("RSA_BW_fixed_clock_0.75_epo_3"
                              ,"RSA_BW_fixed_clock_0.75_epo_4"
                              ,"RSA_BW_fixed_clock_1.2_epo_3"
                              ,"RSA_BW_fixed_clock_1.2_epo_4"))) {
      stop("Did not recognise the model: ", args[2])
    }
  } else if (args[1] == "sensitivity_analysis") {
    if (!is.element(args[2], c("RSA_BW_fixed_clock_0.75_epo_4_inf_dur_7"
                               ,"RSA_BW_fixed_clock_0.75_epo_4_inf_dur_14"))) {
      stop("Did not recognise the model: ", args[2])
    }
  }
  data_set <- args[1]
  model_spec <- args[2]
  xml_filepath <- sprintf("xml/%s/%s.xml", data_set, model_spec)
  plot_filepath <- function(plot_file) {
    sprintf("output/%s/%s/%s", data_set, model_spec, plot_file)
  }
}

# Read a log file generated by BEAST(2) into a suitable dataframe.
read_beast2_log <- function(file, ...) {
  select(read.csv(file, sep = "\t", comment.char = "#", ...), posterior, likelihood, origin, reproductiveNumber, matches("samplingProportion"))
}

log_files <- list.files(pattern = sprintf("%s_combined.log", model_spec), recursive=TRUE)
if (length(log_files) == 0) {
  log_files <- list.files(pattern = sprintf("%s.log", model_spec), recursive = TRUE)
}
num_chains <- length(log_files)
list_of_logs <- map(log_files, read_beast2_log)
log_df <- bind_rows(list_of_logs)
## Need to remove the first sampling proportion because it is a constant and
## including it would break downstream computations.
log_mcmc <- as.mcmc.list(map(list_of_logs,
                             function(df) as.mcmc(select(df, -samplingProportion.1))))


foo_tree <- xmlTreeParse(xml_filepath)$doc$children[["beast"]]
foo_r0_prior <- getNodeSet(foo_tree, sprintf("//prior[@id='reproductiveNumberPrior.s:%s']/LogNormal", model_spec))[[1]]
foo_origin_prior <- getNodeSet(foo_tree, sprintf("//prior[@id='originPrior.s:%s']/LogNormal", model_spec))[[1]]
foo_samplingProportion_prior <- getNodeSet(foo_tree, sprintf("//prior[@id='samplingProportionPrior.s:%s']/Beta", model_spec))[[1]]

r0_prior <- function(x) {
  dlnorm(x,
         meanlog = as.numeric(xmlGetAttr(foo_r0_prior, "M")),
         sdlog = as.numeric(xmlGetAttr(foo_r0_prior, "S")))
}

origin_prior <- function(x) {
  dlnorm(x,
         meanlog = as.numeric(xmlGetAttr(foo_origin_prior, "M")),
         sdlog = as.numeric(xmlGetAttr(foo_origin_prior, "S")))
}

samplingProportion_prior <- function(x) {
  dbeta(x,
         shape1 = as.numeric(xmlGetAttr(foo_samplingProportion_prior, "alpha")),
        shape2 = as.numeric(xmlGetAttr(foo_samplingProportion_prior, "beta")))
}


g_r_naught <- ggplot() +
  geom_histogram(data = log_df, mapping = aes(x = reproductiveNumber, y = ..density.., fill = "Posterior")) +
  stat_function(
    fun = r0_prior,
    geom = "line",
    aes(colour = 'Prior')
  ) +
  scale_fill_manual("", values = c("#595959")) +
  scale_colour_manual("", values = c("#000000")) +
  lims(x = c(1, 5)) +
  theme(legend.title = element_blank())

ggsave(filename = plot_filepath("Re.png"),
       plot = g_r_naught,
       height = 14.8, width = 21.0,
       units = "cm")

g_origin <- ggplot() +
  geom_histogram(data = log_df, mapping = aes(x = origin, y = ..density.., fill = "Posterior")) +
  stat_function(
    fun = origin_prior,
    geom = "line",
    aes(colour = 'Prior')
  ) +
  scale_fill_manual("", values = c("#595959")) +
  scale_colour_manual("", values = c("#000000")) +
  lims(x = c(0, 0.35)) +
  theme(legend.title = element_blank())

ggsave(filename = plot_filepath("origin.png"),
       plot = g_origin,
       height = 14.8, width = 21.0,
       units = "cm")

g_sampling_prop <- ggplot() +
  geom_histogram(data = melt(select(log_df, matches("sampling")), id.vars = c(), value.name = "samplingProportion"),
                 mapping = aes(x = samplingProportion, y = ..density.., fill = "Posterior")) +
  stat_function(
    fun = samplingProportion_prior,
    geom = "line",
    aes(colour = 'Prior')
  ) +
  scale_fill_manual("", values = c("#595959")) +
  scale_colour_manual("", values = c("#000000")) +
  facet_wrap(~variable) +
  theme(legend.title = element_blank())

ggsave(filename = plot_filepath("sampling-proportion.png"),
       plot = g_sampling_prop,
       height = 14.8, width = 21.0,
       units = "cm")

sink(file = plot_filepath("summary.txt"))
cat("Posterior summary\n=================\n")
print(summary(log_mcmc))
cat("Effective sample sizes\n======================\n")
print(effectiveSize(log_mcmc))
if (num_chains > 1) {
  cat("Potential scale reduction factors\n=================================\n")
  print(gelman.diag(log_mcmc))
}
sink()
