library(bdskytools)
library(lubridate)
library(purrr)
library(dplyr)

if (!interactive()) {
  args <- commandArgs(trailingOnly = TRUE)
  
  if (!length(args) %in% c(2, 3)) {
    stop("Bad arguments!")
  } else if (length(args) == 3 && args[3] %in% c("7", "14")) {
    lb_on_mean_infness <- TRUE
    infectious_period <- as.integer(args[3])
  } else {
    lb_on_mean_infness <- FALSE
    infectious_period <- 10 ## default infectious period of 10 days
  }
  
  if (args[1] == "GP") {
    if (!is.element(args[2], c("GP_fixed_clock_0.3_epo_3"
                               ,"GP_fixed_clock_0.3_epo_4"
                               ,"GP_fixed_clock_1.1_epo_3"
                               ,"GP_fixed_clock_1.1_epo_4"))) {
      stop("Did not recognise the model: ", args[2])
    }
    date_last_sample <- '2021-11-26'
  } else if (args[1] == "RSA_BW") {
    if (!is.element(args[2], c("RSA_BW_fixed_clock_0.75_epo_3"
                               ,"RSA_BW_fixed_clock_0.75_epo_4"
                               ,"RSA_BW_fixed_clock_1.2_epo_3"
                               ,"RSA_BW_fixed_clock_1.2_epo_4"))) {
      stop("Did not recognise the model: ", args[2])
    }
    date_last_sample <- '2021-12-05'
  } else if (args[1] == "sensitivity_analysis") {
    if (!is.element(args[2], c("RSA_BW_fixed_clock_0.75_epo_4_inf_dur_7"
                               ,"RSA_BW_fixed_clock_0.75_epo_4_inf_dur_14"))) {
      stop("Did not recognise the model: ", args[2])
    }
    date_last_sample <- '2021-12-05'
  }
  data_set <- args[1]
  model_spec <- args[2]
  plot_filepath <- function(plot_file) {
    sprintf("output/%s/%s/%s", data_set, model_spec, plot_file)
  }
}

## Sampling date of most recent sample
recent <- decimal_date(ymd(date_last_sample))

## Read in a log file generated by BEAST(2)
log.fname <- list.files(pattern = sprintf("%s_combined.log", model_spec), recursive=TRUE)
log.lf <- readLogfile(log.fname, burnin=0)

## We want the bounds on the effective reproductive number
log.Re_sky <- getSkylineSubset(log.lf, "reproductiveNumber")
log.Re_hpd <- getMatrixHPD(log.Re_sky)
cat("\nEffective reproductive number bounds\n")
print(log.Re_hpd)

## We want the bounds on the TMRCA
log.treeHeight_sky <- getSkylineSubset(log.lf, "TreeHeight")
log.treeHeight_time_sky <- recent - log.treeHeight_sky
log.treeHeight_time_hpd <- getMatrixHPD(log.treeHeight_time_sky)
log.treeHeight_time_hpd_date <- format(date_decimal(log.treeHeight_time_hpd), format="%Y-%m-%d")
cat("\nTMRCA date bounds\n")
print(log.treeHeight_time_hpd_date)

## We want the bounds on the exponential growth rate
log.growth_sky <- (log.Re_sky - 1)/infectious_period
log.growth_hpd <- getMatrixHPD(log.growth_sky)
cat("\nGrowth rate bounds\n")
print(log.growth_hpd)

## We want the bounds on the doubling time.
log.dt_sky <- log(2)*infectious_period/(log.Re_sky - 1)
log.dt_hpd <- getMatrixHPD(log.dt_sky)
cat("\nDoubling time bounds\n")
print(log.dt_hpd)

## Output median and 95% HPD intervals to file
sink(file = plot_filepath("parameter-estimates.txt"))
cat("Parameter estimate: median (95% HPD interval)\n===================================================\n")
cat(sprintf('effective productive number: %s (%s - %s)\n', log.Re_hpd[2], log.Re_hpd[1], log.Re_hpd[3]))
cat(sprintf('TMRCA: %s (%s - %s)\n', strsplit(log.treeHeight_time_hpd_date[2], " ")[1], strsplit(log.treeHeight_time_hpd_date[1], " ")[1], strsplit(log.treeHeight_time_hpd_date[3], " ")[1]))
cat(sprintf('exponential growth rate (per day): %s (%s - %s)\n', log.growth_hpd[2], log.growth_hpd[1], log.growth_hpd[3]))
cat(sprintf('doubling time (days): %s (%s - %s)\n', log.dt_hpd[2], log.dt_hpd[1], log.dt_hpd[3]))
sink()
